# docker-compose.yml
# A diretiva "version" foi removida, pois não é mais necessária

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - fenix-network
      - web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lpfenix.rule=Host(`lp.fenixtelecom.com.br`)"
      - "traefik.http.services.lpfenix.loadbalancer.server.port=3000"
      - "traefik.http.routers.lpfenix.entrypoints=web,websecure"
      - "traefik.http.routers.lpfenix.tls=true"
      - "traefik.http.routers.lpfenix.tls.certresolver=letsencrypt"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - fenix-network
      - web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lpfenix-api.rule=Host(`lp.fenixtelecom.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.services.lpfenix-api.loadbalancer.server.port=5000"
      - "traefik.http.routers.lpfenix-api.entrypoints=web,websecure"
      - "traefik.http.routers.lpfenix-api.tls=true"
      - "traefik.http.routers.lpfenix-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lpfenix-api.middlewares=api-strip"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"

  mongodb:
    image: mongo:6
    container_name: lpfenix_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
    networks:
      - fenix-network
      - web
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  fenix-network:
    external: true
  web:
    external: true

volumes:
  mongodb_data:
    name: lpfenix_mongodb_data