# docker-compose.yml
# A diretiva "version" foi removida, pois não é mais necessária

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    # Não expor porta diretamente
    # ports:
    #   - "3000:3000"
    env_file:
      - .env.frontend
    networks:
      - fenix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lpfenix.rule=Host(`lp.fenixtelecom.com.br`)"
      - "traefik.http.services.lpfenix.loadbalancer.server.port=3000"
      - "traefik.http.routers.lpfenix.entrypoints=web,websecure"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5002:5000"
    env_file:
      - .env.backend
    networks:
      - fenix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - mongodb
    # Se quiser expor o backend via Traefik, adicione labels aqui

  # Remover o serviço nginx
  # nginx:
  #   image: nginx:stable-alpine
  #   restart: always
  #   ports:
  #     - "8090:80"
  #   volumes:
  #     - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - fenix-network

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - fenix-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  fenix-network:
    driver: bridge

volumes:
  mongodb_data: