version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`lp.fenixtelecom.com.br`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"

networks:
  traefik_default:
    external: false