global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: web
    swarmMode: false
#  file:
#    directory: "/etc/traefik/config"
#    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "180s"
      lifeCycle:
        requestAcceptGraceTimeout: "10s"
        graceTimeOut: "30s"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "lp.fenixtelecom.com.br"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@fenixtelecom.com.br
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

experimental:
  http3: true

log:
  level: DEBUG
  format: json

accessLog:
  format: json
  bufferingSize: 100

ping:
  entryPoint: traefik

pilot:
  dashboard: false 