http:
  routers:
    lpfenix-web:
      rule: "Host(`lp.fenixtelecom.com.br`)"
      service: "lpfenix-web-service"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 10
      middlewares:
        - retry-middleware
    
    lpfenix-api:
      rule: "Host(`lp.fenixtelecom.com.br`) && PathPrefix(`/api`)"
      service: "lpfenix-api-service"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - retry-middleware
  
  services:
    lpfenix-web-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
        healthCheck:
          path: /
          interval: "10s"
          timeout: "5s"
          retries: 3
        serversTransport: "default-transport"
    
    lpfenix-api-service:
      loadBalancer:
        servers:
          - url: "http://backend:5000"
        healthCheck:
          path: /api/health
          interval: "10s"
          timeout: "5s"
          retries: 3
        serversTransport: "default-transport"

  middlewares:
    retry-middleware:
      retry:
        attempts: 3
        initialInterval: "100ms"

  serversTransports:
    default-transport:
      forwardingTimeouts:
        dialTimeout: "30s"
        responseHeaderTimeout: "30s"
        idleConnTimeout: "180s" 